### PR TITLE
Update cbioportal dependencies to the latest

### LINKED ISSUE #151: Uniprot link is missing in gene view
Seems like we never updated react-mutation-mapper dependency after merging https://github.com/cBioPortal/cbioportal-frontend/pull/4316

### PR DESCRIPTION
**Pull request by onursumer**
Fix #151

### CODE REVIEW

**Review by leexgh — APPROVED** [review]
👍 Thanks!

**Comment by onursumer** [comment]
Looks this PR breaks the Scatter Plot tool tip position and style.

signal_broken_tooltip

**Comment by leexgh** [comment]
Oops... Looks like it only breaks the style in scatter plot, other pages are fine

**Comment by onursumer** [comment]
Good news is scatter plot tooltip issue seems to be fixed.

Bad news is OncoKB tooltip is broken (see https://deploy-preview-152--signaldb.netlify.app/gene/NF1?cancerType=Nerve%20Sheath%20Tumor)
image

**Pull request merged**
